name: go test
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.22', 'stable']
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v -timeout 3m ./... -coverprofile ./coverage.txt

      - name: Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage.txt
          slug: etilite/vkplay-live-api
        if: ${{ matrix.go-version == 'stable' && matrix.os == 'ubuntu-latest' }}